### ISSUE TITLE
TES3MP - stats recorded on login get restored on skill tick

### ISSUE THREAD

**Issue by vikdotdev** [phi-fell/carefree_leveling#3] opened 2023-01-01 15:01 UTC
When player logs in to the server that player is going to have X of magicka and Y of fatigue. On each successful spellcast those stats get reverted to their initial values of X and Y respectively. Attaching the video demonstration below. This is probably true for any skill tick, but it's easier to reproduce with spells.

I suspect this LOC is the cause, but I don't know the lua APIs at all.
```
Players[pid]:LoadAttributes()
```

Mind that this is with client side mods, but the bug is reproducible on vanilla Morrowind too. Toggling the script on the server is the only thing that causes this.

https://user-images.githubusercontent.com/33513522/210175322-edd29e1e-d6e8-49cd-bc53-4bf4c98bc4ba.mp4

I'm using latest v0.8.1 version of TES3MP.

**Comment by vikdotdev** [comment] 2023-01-01 21:53
I was wrong but I was moving into a right direction 😄 

[This line with `Players[pid]:LoadStatsDynamic()`](https://github.com/phi-fell/carefree_leveling/blob/dd66f9295107384043b30f936b13a42b137a0353/pclmp/main.lua#L251) causes this issue to appear. Disabling [retroactive health](https://github.com/phi-fell/carefree_leveling/blob/dd66f9295107384043b30f936b13a42b137a0353/pclmp/main.lua#L236) fixed that for me for the moment.

Removing the call to `recalculate_health` from [here](https://github.com/phi-fell/carefree_leveling/blob/dd66f9295107384043b30f936b13a42b137a0353/pclmp/main.lua#L287) will probably fix that problem for good, albeit for the price of having to wait till next level for the recalculation to happen.

What do you think?

**Comment by phi-fell** [comment] 2023-01-01 22:12
You're indeed correct on the issue and that line was the cause. I changed it to specifically send the base health value instead of all dynamic stats, this seems to fix the issue, but please double check me on that.

I think the other loads I do (of attributes) should be fine, since base attributes shouldn't be changing client side except on events I listen for?  I'm still not 100% certain I understand tes3mp's network model, though, so I could be wrong.

**Comment by vikdotdev** [comment] 2023-01-01 22:58
Looking at the [latest change](https://github.com/phi-fell/carefree_leveling/commit/78423c675568a4fcb3a6c5f148001c2f2156e847) I'd expect to see HP increase in case when skill tick happens and increases owed **Endurance** by +1, but it does not seem to trigger in _real time_. I increased Endurance by 10 that way (to be able to see any numbers since we divide Endurance by 10), but it only updated when I re-connected, although I didn't count if the value was correct. It updated and increased _again_ on the next level-up, even though I selected x5 Willpower, x1 Luck and x1 Intelligence. 

Looks a bit fishy, but I can't see anything wrong in the code.

Absence of immediate update not a huge problem for me personally though.

> I think the other loads I do (of attributes) should be fine, since base attributes shouldn't be changing client side except on events I listen for? I'm still not 100% certain I understand tes3mp's network model, though, so I could be wrong.

Not familiar with it at all, but events look reasonable.

**Comment by phi-fell** [comment] 2023-01-01 23:16
I just pushed a commit, that adds a call to SendStatsDynamic, which might fix that.  I _think_ the issue is that the health isn't being updated client side, and it seemed to work after a quick test on my end.

**Comment by vikdotdev** [comment] 2023-01-02 00:19
That does it. Thank a lot.

**Comment by phi-fell** [comment] 2023-01-02 01:44
Yay! I'm glad it's working now, I'll close this issue for now then.

**Closed by phi-fell** 2023-01-02 01:44 UTC
